### [InfoCepts Data Engineering](https://machinehack.com/hackathons/infocepts_data_engineering_hiring_hackathon/overview)

Author: Victor Krasilnikov

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
DATA_DIR = './InfoCept Participants Data/'

In [4]:
# https://pandas.pydata.org/docs/reference/api/pandas.read_xml.html
data = pd.read_xml(DATA_DIR+"infocept_xml_data_.xml")

In [5]:
data

,index,user_session,total_clicks,total_items,total_cats,max_dwell,mean_dwell,total_duration,click_rate,day_of_week,...,cat_most_viewed,prod_most_viewed_n_times,prod_most_viewed,cat_views_freqs,prod_views_freqs,cat_buys_freqs,prod_buys_freqs,is_purchase,start_time_ts,end_time_ts
0,0,8b69208e-7c64-422d-b670-5b9d82d25606,7,2,1,0.511508,5.995878,166.711175,0.072524,1,...,2053013560982667520,1.0,1030297,0.267802,0.000945,2.337402e-01,0.000690,0,"October 07, 2019 Monday, 00:08:28","October 26, 2019 Saturday, 16:08:29"
1,1,8068596c-a2b8-46ca-8791-e10d70520a1f,7,2,1,7.626576,3.529165,0.434185,0.204248,0,...,2053013602328876544,1.0,36083228,0.140925,0.000946,4.550292e-01,0.000690,0,"October 01, 2019 Tuesday, 15:08:40","October 15, 2019 Tuesday, 20:03:18"
2,2,4d153217-e06d-4581-8924-702c7f757610,2,22,1,3.095637,180.977516,0.935320,0.045982,4,...,2175094838038844672,2.0,1002263,0.000294,0.000945,9.102017e-08,0.000690,0,"October 14, 2019 Monday, 21:17:24","October 23, 2019 Wednesday, 21:56:30"
3,3,e65a6869-fb45-4f34-8482-c80278676d0f,2,2,1,1.089128,4.338280,0.417055,0.028476,0,...,2053013568140556288,3.0,1003257,0.150107,0.000945,4.550279e-01,0.000739,0,"October 05, 2019 Saturday, 21:54:13","October 17, 2019 Thursday, 13:54:29"
4,4,d8206742-06d7-42a2-8163-d70f9dd6cb18,5,1,1,0.329814,3.180891,2.485720,0.094812,5,...,2053013558410492160,1.0,13728056,0.267784,0.000945,4.550284e-01,0.000690,0,"October 09, 2019 Wednesday, 13:33:22","October 29, 2019 Tuesday, 11:51:04"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499995,fee0375f-7432-4912-87dd-355e58ff748e,7,2,1,5.807861,0.135879,0.222842,0.116420,5,...,2053013565659966976,3.0,30023271,0.000002,0.000945,0.000000e+00,0.000689,1,"October 08, 2019 Tuesday, 16:26:45","October 12, 2019 Saturday, 04:46:01"
499996,499996,3dc39db9-b779-4475-a3e7-5e8c63c59e93,2,2,1,0.679914,2.848078,6.560991,0.072760,5,...,2053013560323437056,1.0,12704844,0.000002,0.000945,1.294499e-04,0.000691,1,"October 09, 2019 Wednesday, 06:24:29","October 17, 2019 Thursday, 19:10:13"
499997,499997,d619f46b-cd01-459f-bcac-950aaea63627,6,3,1,0.840349,1.517229,0.023602,0.055101,5,...,2053013561594823168,3.0,1014692,0.267806,0.000962,9.001268e-02,0.000690,1,"October 01, 2019 Tuesday, 09:52:42","October 13, 2019 Sunday, 04:05:35"
499998,499998,efb4fdc8-b413-4c64-9ac3-a0033b091008,4,2,1,3.396826,3.365726,0.020893,0.089165,5,...,2053013558504300032,1.0,19506952,0.000009,0.000946,1.358536e-02,0.000690,1,"October 02, 2019 Wednesday, 18:04:55","October 15, 2019 Tuesday, 03:24:02"
499999,499999,9ae3ff1c-7608-49f7-a227-e948365715f9,3,2,1,6.252938,1.960957,0.024305,0.078291,5,...,2053013577775031552,1.0,1021591,0.267804,0.000962,4.550280e-01,0.000690,1,"October 01, 2019 Tuesday, 03:29:31","October 08, 2019 Tuesday, 05:39:56"

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   index                     500000 non-null  int64
 1   user_session              500000 non-null  object
 2   total_clicks              500000 non-null  int64
 3   total_items               500000 non-null  int64
 4   total_cats                500000 non-null  int64
 5   max_dwell                 500000 non-null  float64
 6   mean_dwell                500000 non-null  float64
 7   total_duration            500000 non-null  float64
 8   click_rate                500000 non-null  float64
 9   day_of_week               500000 non-null  int64
 10  is_weekend                500000 non-null  int64
 11  is_special_day            500000 non-null  int64
 12  time_of_day               500000 non-null  int64
 13  cat_most_viewed_n_times   500000 non-null  float64
 14  cat_most_viewed           500000 non-null  int64
 15  prod_most_viewed_n_times  500000 non-null  float64
 16  prod_most_viewed          500000 non-null  int64
 17  cat_views_freqs           500000 non-null  float64
 18  prod_views_freqs          500000 non-null  float64
 19  cat_buys_freqs            500000 non-null  float64
 20  prod_buys_freqs           500000 non-null  float64
 21  is_purchase               500000 non-null  int64
 22  start_time_ts             500000 non-null  object
 23  end_time_ts               500000 non-null  object
dtypes: float64(10), int64(11), object(3)
memory usage: 91.6+ MB

In [7]:
data.day_of_week.value_counts()

5    260104
0    126565
1     42915
3     24829
4     19270
2     17302
6      9015
Name: day_of_week, dtype: int64

## Data Processing

In [8]:
sub = pd.read_csv(DATA_DIR+"infocept_submission.csv")

In [9]:
sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   total_duration         500000 non-null  int64
 1   is_special_day         500000 non-null  int64
 2   prod_views_freqs       500000 non-null  int64
 3   prod_buys_freqs        500000 non-null  int64
 4   give_big_discount      500000 non-null  int64
 5   prod_views_buys_ratio  500000 non-null  int64
 6   loyalty_points         500000 non-null  int64
 7   total_inventory        500000 non-null  int64
 8   time_spec_points       500000 non-null  int64
dtypes: int64(9)
memory usage: 34.3 MB

In [10]:
# 0. Create 'is_special_day', 'prod_views_freqs' and 'prod_buys_freqs' columns.
#Better without thems !?
sub['is_special_day'] = data['is_special_day']
sub['prod_views_freqs'] = data['prod_views_freqs']
sub['prod_buys_freqs'] = data['prod_buys_freqs']

In [12]:
# 1. Process the "start_time_ts" column to create "time_spec_points" column.
def time_points(x):  
    ans = pd.to_datetime(x).hour
    if ans >= 16:
        ans += 5
    
    return ans
 
sub["time_spec_points"] = data["start_time_ts"].apply(lambda x: time_points(x))

In [13]:
# 2. Reduce the "total_duration"
sub["total_duration"] = data["total_duration"].apply(lambda x: round(x, 2))

In [14]:
# 3.  Add the values of columns  "total_clicks", "total_items", "total_cats"
# to create a new column: "total_inventory".
sub["total_inventory"] = data.apply(lambda row: row.total_clicks + row.total_items + row.total_cats 
                                    if row.total_clicks + row.total_items + row.total_cats <= 10
                                    else (row.total_clicks + row.total_items + row.total_cats) * 2
                                    ,axis=1)

In [15]:
# 4. Create a new column "give_big_discount"
sub["give_big_discount"] = data.apply(lambda row: 1 if  row.day_of_week == 0 and row.is_special_day == 1 else 0, axis=1)

In [21]:
# 5. Create a new column prod_views_buys_ratio 
sub["prod_views_buys_ratio"] = data.apply(lambda row: row["prod_views_freqs"] / row["prod_buys_freqs"], axis=1)

In [17]:
# 6. Create a new column loyalty_points
def loyalty(row):  
    ans = 0
    if row.day_of_week == 0 and row.total_duration > 3: # Sunday?
        ans = 10*(row.total_duration - 3)
    return ans
 
sub["loyalty_points"] = data.apply(lambda row: loyalty(row), axis=1)

In [18]:
# 7. Check the submission file for column details.
sub

,total_duration,is_special_day,prod_views_freqs,prod_buys_freqs,give_big_discount,prod_views_buys_ratio,loyalty_points,total_inventory,time_spec_points
0,166.71,0,0.000945,0.000690,0,1.37,0.0,10,0
1,0.43,0,0.000946,0.000690,0,1.37,0.0,10,15
2,0.94,0,0.000945,0.000690,0,1.37,0.0,50,26
3,0.42,0,0.000945,0.000739,0,1.28,0.0,5,26
4,2.49,0,0.000945,0.000690,0,1.37,0.0,7,13
...,...,...,...,...,...,...,...,...,...
499995,0.22,0,0.000945,0.000689,0,1.37,0.0,10,21
499996,6.56,0,0.000945,0.000691,0,1.37,0.0,5,6
499997,0.02,0,0.000962,0.000690,0,1.39,0.0,10,9
499998,0.02,0,0.000946,0.000690,0,1.37,0.0,7,23
499999,0.02,0,0.000962,0.000690,0,1.39,0.0,6,3

In [19]:
sub.give_big_discount.value_counts()

0    493104
1      6896
Name: give_big_discount, dtype: int64

### Create submission file

In [48]:
sub.to_csv('my_infocept_submission.csv', index=False, header=True)

### Testing

In [19]:
date = "October 07, 2019 Monday, 09:08:28"
pd.to_datetime(date).hour

9

In [28]:
x=10
y=12
print('{} + {} = {}'.format(x+y,x,y))

22 + 10 = 12

In [33]:
log_var = ['total_duration', 'is_special_day', 'prod_views_freqs',
       'prod_buys_freqs', 'give_big_discount', 'prod_views_buys_ratio',
       'loyalty_points', 'total_inventory', 'time_spec_points']
fig = plt.figure(figsize = (24,10))
for j in range(len(log_var)):
    var = log_var[j]
    transformed = "log_" + var
    df[transformed] = np.log10(df[var]+1)
    sub = fig.add_subplot(2, 5, j + 1)
    sub.set_xlabel(var)
    df[transformed].plot(kind = 'hist')

NameError: name 'df' is not defined

In [28]:
sub['prod_views_buys_ratio'][33]

1.3019046058264194